---
- name: check if HELM already installed
  stat:
    path: /usr/local/bin/helm
  register: helm

# Install HELM
- name: Install HELM
  block:
    - name: Copy helm install script
      get_url: 
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
        dest: /tmp/helm.sh
        mode: 0755
    - name: Execute helm install script
      command: bash -c "chmod +x /tmp/helm.sh && DESIRED_VERSION={{ helm_version }} /tmp/helm.sh"
 
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: not helm.stat.exists
